apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volumeContainer
          name: primeiro-volume
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc-2
