apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volumeContainer
          name: primeiro-volume
    - name: jenkins-container
      image: jenkins:alpine
      volumeMounts:
        - mountPath: /volumeContainer
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /D/volume
        type: Directory
