apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-replicaset
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx-stable
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-pod
